export const AuthorizationCode = {
  UNAUTHORIZED: -2,
  UNSAFE_TO_DEACTIVATE: -1,
  SIGNER_IS_SUBJECT: 0,
  SIGNER_IS_CONTROLLER: 1,
  SENDER_IS_SUBJECT: 2,
  SENDER_IS_CONTROLLER: 3,
  ADDRESS_IS_CONTROLLER: 4,
};
