/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  tutorialSidebar: {
    'klayr-did': [
      {
        type: 'autogenerated',
        dirName: 'klayr-did',
      },
    ],
    '@klayr-did/klayr-did-module': [
      {
        type: 'autogenerated',
        dirName: 'klayr-did-module',
      },
    ],
    '@klayr-did/klayr-decentralized-identifier': [
      {
        type: 'autogenerated',
        dirName: 'klayr-decentralized-identifier',
      },
    ],
    '@klayr-did/klayr-verifiable-credentials': [
      {
        type: 'autogenerated',
        dirName: 'klayr-verifiable-credentials',
      },
    ],
  },

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
