name: Codecov

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - 'main'

jobs:
  codecov-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: formsort/action-check-codecov-config@v1

  codecov:
    needs:
      - codecov-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - run: npm ci
      - run: npm run build
      - run: npm run test:ci

      - name: Upload lisk-did coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/lisk-did/coverage/coverage-final.json
          flags: lisk-did
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload lisk-decentralized-identifier coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/lisk-decentralized-identifier/coverage/coverage-final.json
          flags: lisk-decentralized-identifier
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload lisk-did-module coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/lisk-did-module/coverage/coverage-final.json
          flags: lisk-did-module
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload lisk-verifiable-credentials coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/lisk-verifiable-credentials/coverage/coverage-final.json
          flags: lisk-verifiable-credentials
          token: ${{ secrets.CODECOV_TOKEN }}
